server:
  error.whitelabel.enabled: false

spring:
  datasource:
    url: "jdbc:hsqldb:file:data/db"
  web:
    resources:
      cache:
        cachecontrol:
          must-revalidate: true
          cache-private: false
          max-age: 31536000

hanne:
  release: 2020-12-24T23:00:00Z
  date-of-birth: 1996-03-18