apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerst-hanne-2020-tst
  labels:
    app: kerst-hanne-2020-tst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kerst-hanne-2020-tst
  template:
    metadata:
      labels:
        app: kerst-hanne-2020-tst
    spec:
      containers:
      - name: kerst-hanne-2020
        image: "localhost:32000/kerst-hanne-2020:76e27001"
        env:
        - name: "SERVER_SERVLET_CONTEXT_PATH"
          value: "/hanne-tst"
        - name: "HANNE_RELEASE"
          value: "2020-12-24T00:00:00Z"
        ports:
        - name: http
          containerPort: 8080
